version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: pdf_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - pdf_redis_data:/data

volumes:
  pdf_redis_data:
